"""
ChaosOracle protocol constants, contract addresses, and ABIs.

ABIs are loaded from JSON files generated by ``forge build``.  To regenerate
after a contract change run::

    forge build
    python scripts/export_abis.py   # or copy from contracts/out/

All contract addresses target Ethereum Sepolia testnet. RPC URLs are loaded
from environment variables to avoid hardcoding secrets.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

# ---------------------------------------------------------------------------
# ABI loading helper
# ---------------------------------------------------------------------------

# Look for abis/ relative to repo root (local dev) or /app/abis (Docker).
_SHARED_DIR = Path(__file__).resolve().parent
_ABI_DIR = (
    Path(os.environ["ABI_DIR"]) if "ABI_DIR" in os.environ
    else next(
        (p for p in [
            _SHARED_DIR.parent.parent / "abis",   # repo_root/abis  (local dev)
            _SHARED_DIR.parent / "abis",           # /app/abis       (Docker)
        ] if p.is_dir()),
        _SHARED_DIR.parent.parent / "abis",  # fallback
    )
)


def _load_abi(name: str) -> list[dict]:
    """Load a contract ABI from ``<repo_root>/abis/<name>.json``."""
    path = _ABI_DIR / f"{name}.json"
    with open(path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Network configuration
# ---------------------------------------------------------------------------

SEPOLIA_RPC_URL: str = os.environ.get("SEPOLIA_RPC_URL", "")

CHAOSCHAIN_GATEWAY_URL: str = os.environ.get(
    "CHAOSCHAIN_GATEWAY_URL",
    "https://gateway.chaoscha.in",
)

CHAIN_ID: int = 11155111  # Ethereum Sepolia

# ---------------------------------------------------------------------------
# Contract addresses (Sepolia)
# ---------------------------------------------------------------------------

CHAOS_ORACLE_REGISTRY_ADDRESS: str = os.environ.get(
    "CHAOS_ORACLE_REGISTRY_ADDRESS",
    "0x0000000000000000000000000000000000000000",  # placeholder - set after deployment
)

ERC_8004_IDENTITY_ADDRESS: str = os.environ.get(
    "ERC_8004_IDENTITY_ADDRESS",
    "0x0000000000000000000000000000000000000000",  # placeholder - set after deployment
)

REPUTATION_CONTRACT_ADDRESS: str = os.environ.get(
    "REPUTATION_CONTRACT_ADDRESS",
    "0x0000000000000000000000000000000000000000",  # placeholder - set after deployment
)

# ---------------------------------------------------------------------------
# Stake amounts (in wei)
# ---------------------------------------------------------------------------

WORKER_STAKE_WEI: int = 1_000_000_000_000_000   # 0.001 ETH
VERIFIER_STAKE_WEI: int = 1_000_000_000_000_000  # 0.001 ETH

# ---------------------------------------------------------------------------
# ABIs — loaded from forge build output (agents/shared/abis/*.json)
# ---------------------------------------------------------------------------

CHAOS_ORACLE_REGISTRY_ABI: list[dict] = _load_abi("ChaosOracleRegistry")
PREDICTION_SETTLEMENT_LOGIC_ABI: list[dict] = _load_abi("PredictionSettlementLogic")
